networks:
  system-sharebook:
    driver: bridge

volumes:
  db-data:
    driver: local


services:
  postgres:
    image: 'postgres:17.5-alpine'
    container_name: sharebook-postgres
    ports:
      - '5435:5432'
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 20

  sharebook-keycloak-postgres:
    image: postgres:17.5-alpine
    container_name: sharebook-keycloak-postgres
    environment:
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
      POSTGRES_DB: keycloak
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 20

  sharebook-keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: sharebook-keycloak
    command: start-dev --metrics-enabled=true
    ports:
      - "8080:8080"
      - "9000:9000"
    environment:
      JAVA_OPTS: -Dkeycloak.migration.usersExportStrategy=REALM_FILE
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
    depends_on:
      sharebook-keycloak-postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:9000/health/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 30

  sharebook:
    build:
      dockerfile: Dockerfile
    container_name: sharebook
    env_file:
      - .env.docker
    environment:
      SPRING_PROFILES_ACTIVE: docker
#      KEYCLOAK_URL: http://keycloak:8080
#      KEYCLOAK_ISSUER_URI: https://keycloak-host/realms/sharebook
#      SPRING_PROFILES_ACTIVE: docker
#      HOST: persons-api
    ports:
      - "8091:8091"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8091/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10



