server:
  port: 8091

spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:preliquibase/postgresql.sql
  #  config:
#    import: optional:file:.env[.properties],optional:file:system/.env[.properties]
#  datasource:
#    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}
#    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: sharebookschema
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}